/*
* msg_proc.c: implementation of the
* remote procedure "printmessage"
*/

#include <stdio.h>
#include "msg.h" /* msg.h generated by rpcgen */

/* O segundo argumento contém informações sobre o contexto de uma invocação: os números de programa, versão e procedimento, credenciais brutas e canônicas, e um ponteiro de estrutura SVCXPRT (a estrutura SVCXPRT contém informações de transporte. */
int * printmessage_1_svc(char **msg, struct svc_req *req)
{
    static int result; /* must be static */ /* No caso de opções '-' M (multithread) ou '-' A (modo Automático), um ponteiro para o resultado é passado como um terceiro argumento para o procedimento, de modo que o resultado não é declarado no procedimento. */
    
    printf("%s\n", *msg);
    result = 1;
    return (&result);
}
