/*
* rprintmsg.c: remote version
* of "printmsg.c"
*/

// links:
// https://docs.oracle.com/cd/E19048-01/chorus5/806-7022/6jfu47jsg/index.html
// http://users.cs.cf.ac.uk/Dave.Marshall/C/node34.html#ch:rpcgen

#include <stdio.h>
#include "msg.h" /* msg generated by rpcgen */ 

main(int argc, char **argv)
{
    CLIENT *clnt;
    int *result;
    char *server;
    char *message;

    if(argc != 3)
    {
        fprintf(stderr, "usade: %s host message\n", argv[0]);
        exit(1);
    }

    server = argv[1];
    message = argv[2];

    /*
    * Create client "handle" used for
    * calling MESSAFEPROG on the server
    * designated on the command line.
    */
    
    clnt = clnt_create(server, MESSAGEPROG, PRINTMESSAGEVERS, "tcp"); // "tcp", estava "visible", caso queira trocar, salvar e gerar novamente o executavel 

    if (clnt == (CLIENT *)NULL)
    /*
    * Couldn't establish connection
    * with server.
    * Print error message and die.
    */
    {
        clnt_pcreateerror(server);
        exit(1);
    }
    /* Call the remote procedure
    * "printmessage" on the server
    */
    result = printmessage_1(&message, clnt);
    if (result == (int *)NULL)
    /*
      * An error occurred while calling
      * the server.
      * Print error message and die.
    */
    {
        clnt_perror(clnt, server);
        exit(1);
    }
    /* Okay, we successfuly called
    * the remote procedure.
    */

    if (*result == 0) 
        /*
        * Server was unable to print
        * our message.
        * Print error message and die.
        */
    {
        fprintf(stderr, "%s: could not print your message\n",argv[0]);
        exit(1);
    }

    /* The message got printed on the 
    * server's console
    */
    printf("Message delivered to %s\n", server);
    clnt_destroy(clnt);
    exit(0);
}